### ISSUE TITLE
Automatic deceptive attack

### ISSUE THREAD

**Issue by Zuljita** [MaxWilson/CageFight#1]
It might be good to factor in an automatic deceptive attack on attackers who have skill higher than 16, providing defense penalties.  Most monsters with a skill higher than 16 should be using either hit locations or deceptive attacks.   Given that hit locations would dramatically increase complexity, just starting with deceptive makes more sense.

**Comment by dripton** [comment]
As a refinement, you also might want to deceptive attack down to lower than 16 when it helps increase the overall chance of a damaging hit, or the average damage.  My rule of thumb when I don't have my spreadsheet handy (or don't know the target's defenses) is to DA down to about skill 12, but of course there are cases where it makes more sense to stay at 16 and crit-fish, and cases where you want to DA all the way down to 10.

**Comment by MaxWilson** [comment]
@dripton good thoughts. I have design questions that I'd like to talk over first. If you want to use the more intelligent behavior (calculating exact percentages), should all monsters do that or only the smart ones? Or should it be a property of fight setup and not of individual monsters? What would the UI look like? 

Initially for today I'll go with Zuljita's suggestion (excess skill over 16 goes to Deceptive) because it doesn't need any UI design but I'll leave this issue open until we settle the larger question.

**Comment by Zuljita** [comment]
It's not always easy to determine what the best bang for buck is in this sort of scenario.  I'd probably want to use a tool just like this one Monte Carlo simulation style to try to figure that out... If we're going to apply logic to it, you could do things like IQ roll when you've failed to hit x times in a row before you change tactics, but... that seems like a lot of complexity for a simple tool.  If the goal is to get full combat simulation, you can get very complicated very quickly.  Is that in scope?

**Comment by Zuljita** [comment]
I almost tried to suggest hit locations, but backed away from it after I realized how many variables we'd be talking about.

**Comment by MaxWilson** [comment]
> It's not always easy to determine what the best bang for buck is in this sort of scenario. I'd probably want to use a tool just like this one Monte Carlo simulation style to try to figure that out... If we're going to apply logic to it, you could do things like IQ roll when you've failed to hit x times in a row before you change tactics, but... that seems like a lot of complexity for a simple tool. If the goal is to get full combat simulation, you can get very complicated very quickly. Is that in scope?

Full (and interactive) combat simulation is a different app, Shining Sword, that I've been working on for a while. CageFight is just a simplistic outgrowth of that. So no, full combat simulation is not a goal for CageFight.

**Comment by MaxWilson** [comment]
Deceptive Attack down to 16 is now implemented. I also added [Inigo Montoya](https://github.com/MaxWilson/CageFight/blob/9577819adffb1d002b81f9cdafda489ca26793cb/src/CageFight/Domain/Domain.fs#L200) to the default monsters list just for fun.

> Inigo Montoya: ST 13 DX 16 IQ 11 HT 12 Speed 8.5 Dodge 12 Parry 17F DR 1 Weapon Master Skill 22 thr+2 imp Extra Attack 1

Turns out he's got about around 3-6 orcpower.

**Comment by MaxWilson** [comment]
This issue has been quiet for a while, and the original issue of automatic deceptive attack is now implemented. @dripton if you or anyone else would like a more optimized, intelligent use of deceptive attack would you please open a new issue?
